#Version del docker-compose (cada quien establece su versión)
version: '0.1'

services:
  db:
    build: ./database/db_Login
    ports:
      - "3306:3306"
    container_name: db

    #Consulta el estado del servicio para que el que es dependiente inicie cuando todo este ok!
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -proot || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 15


  server:

    #Ubicacion del dockerfile
    build: ./
    ports:
      - "8081:8081"

    #nombre asignar al contenedor
    container_name: server

    #variables de entorno
    environment:
      - host=0.0.0.0/0
      - user=root
      - password=root
      - database=login
    
    #Establece dependencia (este servicio depende del servicio db y de que db arroje un estado healthy)

    depends_on:
      db:
        condition: service_healthy
        
    # Comando para esperar a que la base de datos esté disponible antes de ejecutar el script
    entrypoint: /app/wait-for-it.sh db:3306 -- /app/start-app.sh
    #Reinicia el servicio en caso de fallo hasta que se pueda conectar a la base de datos
    restart: on-failure
    