#Version del docker-compose (cada quien establece su versión)
version: '0.1'

services:
  db:
    build: ./database/db_Login
    ports:
      - "3306:3306"
    container_name: db


  server:

    #Ubicacion del dockerfile
    build: ./
    ports:
      - "8081:8081"

    #nombre asignar al contenedor
    container_name: server

    #variables de entorno
    environment:
      - host=localhost
      - user=root
      - password=root
      - database=login
    
    #Establece dependencia (este servicio depende del servicio db)
    depends_on:
      - db
    #Reinicia el servicio en caso de fallo hasta que se pueda conectar a la base de datos
    restart: on-failure
    